# Generated by Django 4.2.10 on 2024-02-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_field', models.IntegerField()),
                ('second_field', models.IntegerField(null=True)),
            ],
        ),
    ]
