# Generated by Django 4.2.10 on 2024-02-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_drop_column', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropcolumn',
            name='second_field',
            field=models.IntegerField(null=True),
        ),
    ]
